name: Test pull requrest

on:
  pull_request:
      branches:
        - master
 
jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pytest
    - name: Install dependencies
      run: |
        python -m pytest -vv test
